export const mediaHtml = `<!doctype html><html lang="uk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Створити відео · Veil of Ages</title><link rel="stylesheet" href="/media/style.css"><script src="/media/app.js" defer></script></head><body><main><p class="brand">VEIL OF AGES</p><h1>Картинка + музика → відео</h1><p>Сервер створить MP4 1280 × 720. Картинка зберігає пропорції, аудіо звучить повністю. Для тесту — до 5 хвилин, одне завдання одночасно.</p><label>Секрет налаштування Render<input id="secret" type="password" autocomplete="off" placeholder="YOUTUBE_SETUP_SECRET"></label><form id="create"><label>Картинка JPG або PNG — до 8 МіБ<input id="image" type="file" accept=".jpg,.jpeg,.png" required></label><label>Аудіо MP3 або WAV — до 25 МіБ<input id="audio" type="file" accept=".mp3,.wav" required></label><button id="createButton">Створити відео</button></form><p id="status" role="status" aria-live="polite"></p><section id="preview" hidden><h2>Перегляньте результат</h2><video id="video" controls></video><p><a id="download" download="veil-of-ages.mp4">Зберегти MP4 на комп’ютер</a></p><form id="publish"><label>Назва на YouTube<input id="title" maxlength="100" value="Veil of Ages — тестове відео" required></label><label>Відео створене спеціально для дітей?<select id="children" required><option value="">Оберіть</option><option value="no">Ні</option><option value="yes">Так</option></select></label><label>Містить музику або реалістичний контент, згенерований ШІ?<select id="synthetic" required><option value="">Оберіть</option><option value="yes">Так</option><option value="no">Ні</option></select></label><label><input type="checkbox" required> Маю право завантажити цю музику та картинку й підтверджую відправлення у підключений канал.</label><button id="publishButton">Завантажити приватно на YouTube</button></form><p id="publishStatus" role="status" aria-live="polite"></p><a id="youtube" hidden target="_blank" rel="noopener noreferrer">Відкрити ролик на YouTube</a></section><p>Створення не публікує відео. Для відправлення потрібне окреме натискання. Тимчасові файли видаляються приблизно через 30 хвилин після завершення; при перезапуску Render результат може зникнути. Оригінали зберігайте на комп’ютері.</p><a href="/youtube/upload">Завантажити вже готовий MP4</a></main></body></html>`;

export const mediaCss = `body{margin:0;background:#0c0e16;color:#f4f4fa;font:17px system-ui}main{max-width:760px;margin:40px auto;padding:24px}h1{font-size:clamp(28px,5vw,44px)}p{line-height:1.65;color:#b7bccd}.brand{color:#50dafa;font-weight:700;letter-spacing:2px}label{display:block;margin:22px 0}input:not([type=checkbox]),select{display:block;box-sizing:border-box;width:100%;margin-top:8px;padding:12px;border:1px solid #454a63;border-radius:8px;background:#191d2b;color:#fff}button{padding:15px 22px;background:#7565ff;color:white;border:0;border-radius:24px;font:inherit;cursor:pointer}button:disabled{opacity:.5}a{color:#8ae3ff}video{width:100%;max-height:480px;background:#000}section{border-top:1px solid #454a63;margin-top:24px;padding-top:16px}`;

export const mediaScript = `const el=id=>document.getElementById(id);let blob=null,objectUrl=null,active=false;
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function json(response){let data;try{data=await response.json();}catch{throw new Error('Сервер не відповів. Перевірте стан Render.');}if(!response.ok)throw new Error(data.error||'Запит не виконано.');return data;}
el('create').addEventListener('submit',async event=>{event.preventDefault();if(active)return;const secret=el('secret').value;if(!secret){el('status').textContent='Введіть YOUTUBE_SETUP_SECRET.';return;}const image=el('image').files[0],audio=el('audio').files[0];if(!image||!audio||image.size>8388608||audio.size>26214400){el('status').textContent='Перевірте розміри файлів: картинка до 8 МіБ, аудіо до 25 МіБ.';return;}active=true;el('createButton').disabled=true;el('preview').hidden=true;blob=null;if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null;}el('youtube').hidden=true;el('publishStatus').textContent='';el('status').textContent='Передаємо файли на Render…';
try{const body=new FormData();body.append('image',image);body.append('audio',audio);const job=await json(await fetch('/media/jobs',{method:'POST',headers:{'X-Setup-Secret':secret},body}));el('status').textContent='Сервер створює відео. На безкоштовному Render це може тривати кілька хвилин. Не закривайте сторінку.';const deadline=Date.now()+12*60000;
while(true){if(Date.now()>deadline)throw new Error('Очікування перевищило 12 хвилин. Сервер міг перезапуститися; перевірте Render.');await pause(10000);const state=await json(await fetch('/media/jobs/'+job.id,{headers:{'X-Setup-Secret':secret}}));if(state.state==='error')throw new Error(state.error);if(state.state==='ready')break;}
el('status').textContent='Відео готове, завантажуємо попередній перегляд…';const result=await fetch('/media/jobs/'+job.id+'/file',{headers:{'X-Setup-Secret':secret}});if(!result.ok){await json(result);throw new Error('Не вдалося отримати відео.');}blob=await result.blob();objectUrl=URL.createObjectURL(blob);el('video').src=objectUrl;el('download').href=objectUrl;el('preview').hidden=false;el('status').textContent='Готово! Перевірте зображення й звук. На YouTube ще нічого не відправлено.';}
catch(error){el('status').textContent=error.message||'Не вдалося створити відео.';}finally{active=false;el('createButton').disabled=false;}});
el('publish').addEventListener('submit',async event=>{event.preventDefault();if(active||!blob)return;const secret=el('secret').value;if(!secret){el('publishStatus').textContent='Введіть секрет налаштування зверху.';return;}active=true;el('createButton').disabled=true;el('publishButton').disabled=true;el('publishStatus').textContent='Передаємо приватне відео на YouTube…';try{const query=new URLSearchParams({title:el('title').value,children:el('children').value,synthetic:el('synthetic').value});const data=await json(await fetch('/youtube/upload?'+query,{method:'POST',headers:{'Content-Type':'video/mp4','X-Setup-Secret':secret},body:blob}));if(!/^[A-Za-z0-9_-]{11}$/.test(data.videoId))throw new Error('Не вдалося підтвердити результат. Перевірте YouTube Studio.');el('youtube').href='https://www.youtube.com/watch?v='+data.videoId;el('youtube').hidden=false;el('publishStatus').textContent=data.duplicate?'Цей файл уже завантажено. Нову копію не створено.':'YouTube прийняв приватне відео. Обробка може ще тривати.';}catch(error){el('publishStatus').textContent=error.message||'Зв’язок перервався. Перевірте YouTube Studio перед повтором.';}finally{active=false;el('createButton').disabled=false;el('publishButton').disabled=false;el('secret').value='';}});
window.addEventListener('beforeunload',event=>{if(active){event.preventDefault();event.returnValue='';}});`;
